#This R script creates a new function process_and_plot_gyro that 
#processes and plots gyroscope data. 
#It then reads the CSV files generated by the 'ConvertGyroData' function, 
#processes the data, and creates 3D plots for each gyroscope data file 
#in the "Processed" directory.
library(tidyverse)
library(plotly)

# Detect the script's directory
if (interactive()) {
  # If running the script in RStudio
  script_path <- rstudioapi::getSourceEditorContext()$path
} else {
  # If running the script from the command line
  script_path <- commandArgs(trailingOnly = TRUE)[1]
}
script_dir <- dirname(tools::file_path_as_absolute(script_path))

# Define the base path
base_path <- file.path(script_dir, "Converted")

process_and_plot_gyro <- function(df, file_name, base_path, processed_dir) {
  # Convert data types
  df <- df %>%
    mutate(
      ID = as.integer(ID),
      SECOND = as.numeric(Second),
      GYRO_X = as.numeric(GYRO_X),
      GYRO_Y = as.numeric(GYRO_Y),
      GYRO_Z = as.numeric(GYRO_Z)
    )
  
  # Create the plotly plot
  plot <- plot_ly(df, x = ~ID, y = "X", z = ~GYRO_X, type = "scatter3d", mode = "markers", name = "X", marker = list(size = 3, color = "blue")) %>%
    add_trace(x = ~ID, y = "Y", z = ~GYRO_Y, type = "scatter3d", mode = "markers", name = "Y", marker = list(size = 3, color = "green")) %>%
    add_trace(x = ~ID, y = "Z", z = ~GYRO_Z, type = "scatter3d", mode = "markers", name = "Z", marker = list(size = 3, color = "red")) %>%
    layout(
      title = "Gyroscope Data",
      scene = list(
        xaxis = list(title = "Unique ID"),
        yaxis = list(title = "Gyroscope Axis"),
        zaxis = list(title = "Angular Velocity (deg/sec)")
      )
    )
  
  # Save the plotly plot as an HTML file
  htmlwidgets::saveWidget(plot, file.path(processed_dir, paste0(file_name, "_gyroscope_data_3d_plot.html")))
}

# Create a new directory for processed files
processed_dir <- file.path(base_path, "Processed/Gyroscope")
if (!dir.exists(processed_dir)) {
  dir.create(processed_dir, recursive = TRUE)
}

# Read, process, and plot CSV files
file_paths <- list.files(
  path = base_path,
  pattern = "Gyroscope(\\d+)\\.csv",
  full.names = TRUE
)

for (file_path in file_paths) {
  file <- read.csv(file_path, header = TRUE, sep = ",")
  df <- file[, colSums(is.na(file)) < nrow(file)]
  
  # Extract the file number from the file name
  file_name <- gsub("^Gyroscope(\\d+)\\.csv$", "Gyroscope\\1", basename(file_path))
  
  # Pass the base path and processed directory to the function
  process_and_plot_gyro(df, file_name, base_path, processed_dir)
}
